export const TextActionTypes = {
  CHANGE_TEXT: "CHANGE_TEXT",
  SAVE_TEXT_TO_FILE: "SAVE_TEXT_TO_FILE",
  SWITCH_CURRENT_FILE: "SWITCH_CURRENT_FILE",
  ADD_FOLDER: "ADD_FOLDER",
  ADD_FILE: "ADD_FILE",
  CHANGE_FOLDER_NAME: "CHANGE_FOLDER_NAME",
  CHANGE_FILE_NAME: "CHANGE_FILE_NAME"
};
