export const screenActionTypes = {
  HANDLE_WINDOW_RESIZE: "HANDLE_WINDOW_RESIZE",
  TOGGLE_EDITOR_VIEWER: "TOGGLE_EDITOR_VIEWER",
  TOGGLE_FOLDERS: "TOGGLE_FOLDERS",
  SWITCH_RESIZER_CLICKED: "SWITCH_RESIZER_CLICKED"
};
