export const userActionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_IN_DEFAULT: "SIGN_IN_DEFAULT",
  CHANGE_TEXT: "CHANGE_TEXT",
  SAVE_TEXT_TO_FILE: "SAVE_TEXT_TO_FILE",
  SWITCH_CURRENT_FILE: "SWITCH_CURRENT_FILE",
  ADD_FOLDER: "ADD_FOLDER",
  ADD_FILE: "ADD_FILE",
  CHANGE_FOLDER_NAME: "CHANGE_FOLDER_NAME",
  CHANGE_FILE_NAME: "CHANGE_FILE_NAME",
  SET_FOLDER_CHANGING_NAME: "SET_FOLDER_CHANGING_NAME",
  SET_FOLDER_CHANGING_NAME_INPUT: "SET_FOLDER_CHANGING_NAME_INPUT",
  SET_FILE_CHANGING_NAME: "SET_FILE_CHANGING_NAME",
  SET_FILE_CHANGING_NAME_INPUT: "SET_FILE_CHANGING_NAME_INPUT"
};
